class Tags:

    activity_tags = {
        "BaseballPitch": ["sports", "baseball", "throwing", "outdoor"],
        "Basketball": ["sports", "ballgame", "team", "court"],
        "BenchPress": ["gym", "strength", "weights", "indoor"],
        "Biking": ["outdoor", "cycling", "exercise", "movement"],
        "Billiards": ["indoor", "precision", "cue", "recreational"],
        "BreastStroke": ["swimming", "water", "technique", "exercise"],
        "CleanAndJerk": ["weightlifting", "power", "gym", "competition"],
        "Diving": ["water", "acrobatic", "sports", "precision"],
        "Drumming": ["music", "percussion", "rhythm", "instrument"],
        "Fencing": ["combat", "sports", "sword", "agility"],
        "GolfSwing": ["sports", "outdoor", "swing", "golf"],
        "HighJump": ["athletics", "jump", "track", "height"],
        "HorseRace": ["equestrian", "racing", "speed", "outdoor"],
        "HorseRiding": ["equestrian", "outdoor", "balance", "motion"],
        "HulaHoop": ["dance", "fun", "circular", "fitness"],
        "JavelinThrow": ["track", "throwing", "sports", "outdoor"],
        "JugglingBalls": ["circus", "skills", "coordination", "performance"],
        "JumpingJack": ["exercise", "cardio", "warmup", "fitness"],
        "JumpRope": ["cardio", "fitness", "coordination", "training"],
        "Kayaking": ["water", "paddle", "adventure", "outdoor"],
        "Lunges": ["workout", "legday", "fitness", "gym"],
        "MilitaryParade": ["discipline", "marching", "uniform", "ceremony"],
        "Mixing": ["DJ", "music", "sound", "entertainment"],
        "Nunchucks": ["martial arts", "weapon", "skills", "training"],
        "PizzaTossing": ["cooking", "kitchen", "dough", "skills"],
        "PlayingGuitar": ["music", "instrument", "strings", "performance"],
        "PlayingPiano": ["music", "keyboard", "instrument", "indoors"],
        "PlayingTabla": ["music", "drums", "rhythm", "traditional"],
        "PlayingViolin": ["music", "strings", "bow", "melody"],
        "PoleVault": ["track", "jump", "athletics", "height"],
        "PommelHorse": ["gymnastics", "strength", "balance", "indoor"],
        "PullUps": ["strength", "upperbody", "gym", "fitness"],
        "Punch": ["boxing", "combat", "fist", "training"],
        "PushUps": ["strength", "exercise", "bodyweight", "fitness"],
        "RockClimbingIndoor": ["adventure", "climbing", "indoor", "grip"],
        "RopeClimbing": ["strength", "fitness", "grip", "vertical"],
        "Rowing": ["water", "team", "exercise", "coordination"],
        "SalsaSpin": ["dance", "spin", "latin", "rhythm"],
        "SkateBoarding": ["street", "tricks", "outdoor", "board"],
        "Skiing": ["snow", "mountain", "speed", "adventure"],
        "Skijet": ["water", "motor", "speed", "adventure"],
        "SoccerJuggling": ["soccer", "skills", "footwork", "ball"],
        "Swing": ["recreation", "outdoor", "motion", "relaxation"],
        "TaiChi": ["meditation", "martialarts", "balance", "slowmotion"],
        "TennisSwing": ["racket", "sports", "tennis", "court"],
        "ThrowDiscus": ["track", "field", "throw", "strength"],
        "TrampolineJumping": ["bounce", "fun", "gymnastics", "indoor"],
        "VolleyballSpiking": ["sports", "team", "net", "jump"],
        "WalkingWithDog": ["pet", "leisure", "outdoor", "casual"],
        "YoYo": ["toy", "skill", "trick", "handeye"],
    }
